spring:
  application:
    name: market-forge

server:
  port: 8080


mybatis-plus:
  mapper-locations:
    - classpath*:/mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    jdbc-type-for-null: "NULL"

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    root: info

market-forge:
  thread-pool:
    enabled: true
    pools:
      message-task:
        core-pool-size: 4
        maximum-pool-size: 8
        queue-capacity: 1000
        keep-alive-seconds: 60
        await-termination-seconds: 30
        rejected-policy: caller-runs
      award-grant:
        core-pool-size: 4
        maximum-pool-size: 16
        queue-capacity: 2000
        keep-alive-seconds: 60
        await-termination-seconds: 30
        rejected-policy: abort
