spring:

  application:
    name: market-forge

  profiles:
    active: dev

server:
  port: 8080


mybatis-plus:
  mapper-locations:
    - classpath*:/mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    jdbc-type-for-null: "NULL"

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    root: info
